services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: mise-sqlserver
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Mise@2025!
        ports:
            - "1433:1433"
        volumes:
            - mise_data:/var/opt/mssql
        restart: always

volumes:
    mise_data:
        name: mise_data
